---
- hosts: all
  sudo: True
  tasks:
  - name: copy package file
    copy: src={{ pkgfile }} dest=/tmp
  - name: install rpm package
    command: rpm -i /tmp/{{ pkgname }}
    when: ansible_os_family == 'RedHat'
  - name: install deb package
    command: dpkg -i /tmp/{{ pkgname }}
    when: ansible_os_family != 'RedHat'
  - name: restart service
    service: name=infinidb-em state=restarted
  - name: wait for server to be up
    sudo: False
    local_action: wait_for port=9090 host={{ inventory_hostname }} delay=5 timeout=20
    